### ISSUE TITLE
Eldorado always detected as running

### ISSUE THREAD

**Issue by Catarax** [PlGGS/Halo-Online-Split-Screen#1]
![screenshot_1](https://cloud.githubusercontent.com/assets/3964507/18092913/684f2a3a-6ece-11e6-9f65-4e177a7a3b51.png)

After a reboot or whatever, i'll always get this message and can't try the mod.
There is no eldorado or dewrito updater in my process list.

Windows 10 Anniversary

**Comment by PlGGS** [comment]
Many people are having this issue. Here is a link to a version that doesn't check to see whether or not any instances are running. Use with caution: http://www.mediafire.com/download/e39c5218k0xaz61/HOSS_0.2.1.4_%28NoCheck%29.zip
