### ISSUE TITLE
Make it work for 0.6

### ISSUE THREAD

**Issue by maxime4000** [PlGGS/Halo-Online-Split-Screen#2]
I've been hacking your tools for less than 2 hours and already made it possible to execute 0.6 in split screen but I hack my way to make it possible as it was popup message like game outdated. I did some commenting if (//...productversion == "0.5.1.1" and things like that, but I also did need to remove the signing (as it wasnt wanting to compile) to make it work. So it might be better if the push was from you.
Here is where I change files to hack my way.
frmMain.cs:280
frmMain.cs:320

# Note
When your copying the files, it remove HOSS of the copying list but if it's an other folder ex: Released, it will copy Release recursively until you have no space, would be worth to check the current folder to not copy it.
Also, the profiles features is kinda broken, but you can edit thing in game and after relaunch, it's fine. Unless I thought it was something it wasn't.

Nice hack :)

**Comment by PlGGS** [comment]
Thanks for the effort, but I'm actually currently working on a rewrite of the entire application for 0.6. You can find it here: https://github.com/PlGGS/Halo-Online-Multi-Instance

**Comment by PlGGS** [comment]
Thanks for the effort, but I'm actually currently working on a rewrite of the entire application for 0.6. You can find it here: https://github.com/PlGGS/Halo-Online-Multi-Instance

**Comment by maxime4000** [comment]
Haven't give responds for a while but I try your application, and it harder to use, could you make a tutorial on how to use it because This one is easier to make it work than your new one.

**Comment by PlGGS** [comment]
I'm rewriting the whole thing again. Trying to have it done by tonight

https://github.com/PlGGS/ElDewrito-Multi-Instance

**Comment by maxime4000** [comment]
No need to make it work tonight, I'll hack my way to make it work on 0.6.1.0 for tonight :P but thanks for quick respond. Anyway it's the New Year's Eve try celebrate instead of fixing that ;)

**Comment by PlGGS** [comment]
Okay I just feel bad for you bc this old codebase is so badddddddddd lmao
