### ISSUE TITLE
Halo Online 0.6.1 doesn't work

### ISSUE THREAD

**Issue by domportera** [PlGGS/Halo-Online-Split-Screen#3]
Currently I can't run the compiled version with Halo Online 0.6.1, it says it's out of date, which tells me it hasn't been updated for 0.6. Is there anything I can do on my side to make it compatible?

**Comment by PlGGS** [comment]
Hey yeah I have a newer repo titled eldewrito split screen one sec

**Comment by PlGGS** [comment]
Oh sorry it's eldewrito multi instance

**Comment by PlGGS** [comment]
https://github.com/PlGGS/ElDewrito-Multi-Instance

**Comment by PlGGS** [comment]
It doesn't place instances properly on one screen like the old one, but it's much better and way more efficient

**Comment by domportera** [comment]
perfect, thanks so much!

**Comment by domportera** [comment]
also thanks for getting back like instantaneously that's amazing

**Comment by PlGGS** [comment]
No problem! Yeah no worries
